#!/usr/bin/nft -f

define external_nic = eth0
define vpn_nic = wg0

define vpn_port = 51871
define chadserver_ip = 10.0.0.99
define git_server_ip = 10.0.0.96
define vps_vpn_ip = 192.168.0.254
define matrix_federation_port = 8448

destroy table inet filter
table inet filter {
  chain input {
    type filter hook input priority filter
    policy drop

    ct state invalid drop
    ct state { established, related } accept
    iif lo accept

    ip protocol icmp icmp type { echo-reply, echo-request, destination-unreachable, time-exceeded, parameter-problem } accept

    iifname $vpn_nic tcp dport ssh ct state new accept comment "ssh over wireguard"
    udp dport $vpn_port ct state new accept comment "wireguard"

    drop
  }

  chain forward {
    type filter hook forward priority filter
    policy drop

    ct state invalid drop
    ct state { established, related } accept

    iifname $external_nic oifname $vpn_nic ip daddr $git_server_ip tcp dport ssh ct state new accept comment "public git to chadserver"
    iifname $external_nic oifname $vpn_nic ip daddr $chadserver_ip tcp dport { http, https, $matrix_federation_port } ct state new accept comment "public web to chadserver"

    iifname $vpn_nic accept comment "vpn forwarding"
  }

  chain output {
    type filter hook output priority filter
    policy accept
  }
}

destroy table ip nat
table ip nat {
  chain prerouting {
    type nat hook prerouting priority dstnat

    iifname $external_nic tcp dport ssh dnat to $git_server_ip
    iifname $external_nic tcp dport { http, https, $matrix_federation_port } dnat to $chadserver_ip
  }

  chain postrouting {
    type nat hook postrouting priority srcnat

    oifname $vpn_nic ip daddr $git_server_ip tcp dport ssh snat to $vps_vpn_ip
    oifname $vpn_nic ip daddr $chadserver_ip tcp dport { http, https, $matrix_federation_port } snat to $vps_vpn_ip
    oifname $external_nic ip saddr 192.168.0.0/24 masquerade
  }
}
