[Interface]
Address = 192.168.0.102/32
ListenPort = 51871
DNS = 10.0.0.1
PostUp = wg set %i private-key /etc/wireguard/%i.private.key

# chadvm0
[Peer]
PublicKey = PUBLIC_KEY_chadvm0.lan
AllowedIPs = 192.168.0.0/24, 10.0.0.0/16
Endpoint = vpn.voegele.me:51871
