#!/usr/bin/nft -f

define internal_nic = enp1s0f1
define external_nic = enp1s0f0
define vpn_nic = wg0

define vpn_port = 51871

destroy table inet filter
table inet filter {
  chain input {
    type filter hook input priority 0

    ip protocol icmp icmp type { echo-reply, echo-request, destination-unreachable, time-exceeded, parameter-problem } meter router-icmp { ip saddr limit rate 1/second } accept
    ip protocol icmp reject with icmp type port-unreachable

    ct state { established, related } accept
    ct state invalid drop

    iif lo accept

    iifname { $internal_nic, $vpn_nic } tcp dport ssh ct state new accept comment "ssh"
    iifname { $internal_nic, $vpn_nic } meta l4proto { tcp, udp } th dport domain ct state new accept comment "dns"
    iifname $external_nic udp dport $vpn_port ct state new accept comment "vpn"

    drop
  }

  chain forward {
    type filter hook forward priority 0

    oifname $external_nic tcp flags syn tcp option maxseg size set rt mtu

    ct state { established, related } accept
    ct state invalid drop

    iif { lo, $internal_nic } accept
    iifname $vpn_nic accept

    drop
  }

  chain output {
    type filter hook output priority 0
  }
}

destroy table ip nat
table ip nat {
  chain postrouting {
    type nat hook postrouting priority 100
    oifname $external_nic ip saddr 10.0.0.0/16 masquerade
    oifname $external_nic ip saddr 192.168.0.0/24 masquerade
  }
}
