[Interface]
Address = 192.168.0.1/32
ListenPort = 51871
PostUp = wg set %i private-key /etc/wireguard/%i.private.key

# chadvm0
[Peer]
PublicKey = PUBLIC_KEY_chadvm0.lan
AllowedIPs = 192.168.0.0/24
Endpoint = vpn.voegele.me:51871
PersistentKeepalive = 25
